theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: teal
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.tabs.link
  repo_url: https://github.com/scolastico-dev/s.Default # HERE is configuration needed!
  repo_name: scolastico-dev/s.Default # HERE is configuration needed!
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scolastico-dev/s.Default # HERE is configuration needed!
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
copyright: 'Copyright &copy; 2021 - 2021 Joschua Becker EDV &#124; View instead in: <a href="dokka/index.html">Dokka Docs</a> or <a href="javadoc/index.html">JavaDoc</a>'
site_name: My Docs # HERE is configuration needed!
