name: Main Workflow Run

on:
  push:
    branches: [main]
  release:
    types: [created]
  pull_request:
    types: [opened]
    branches: [main]
  schedule:
    - cron: '25 1 * * 4'

# Secrets which are needed for CI_DOCS_TO_SERVER:
#   SSH_HOST: An ip address.
#   SSH_PORT: The port for ssh. Default is 22.
#   SSH_USER: The username for the login.
#   SSH_PRIVATE_KEY: The private key for the login.
#   DOCUMENTATION_REMOTE_HOST_PATH: The path where to store the documentation.
#   SSH_KNOWN_HOST: To get the known host execute: ssh-keyscan -H <IP_ADRESS>
# OR:
#   Enable GitHub pages and set the value of the env 'CI_DOCS_TO_GH_PAGES' to true.

env:
  CI_DOCS_TO_SERVER: false
  CI_DOCS_TO_GH_PAGES: false
  USERNAME: scolastico-dev
  REPO: s.Default
  JAR_NAME: example-shadow.jar

jobs:
  prepare:
    name: Prepare Workflow
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Download repo from GitHub
      - uses: pozetroninc/github-action-get-latest-release@master
        id: version
        if: github.event_name == 'release'
        name: Get latest version name from GitHub
        with:
          repository: ${{ env.USERNAME }}/${{ env.REPO }}
          excludes: draft
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set version in build.gradle.kts
        uses: datamonsters/replace-action@v2
        if: github.event_name == 'release'
        with:
          files: build.gradle.kts
          replacements: dev-snapshot=${{ steps.version.outputs.release }}
      - name: Set version in VERSION file
        uses: datamonsters/replace-action@v2
        if: github.event_name == 'release'
        with:
          files: src/main/resources/staticVars/VERSION
          replacements: dev-snapshot=${{ steps.version.outputs.release }}
      - name: Set version in build.gradle.kts
        uses: datamonsters/replace-action@v2
        if: github.event_name != 'release'
        with:
          files: build.gradle.kts
          replacements: dev-snapshot=dev-snapshot-${{ steps.vars.outputs.sha_short }}
      - name: Set version in VERSION file
        uses: datamonsters/replace-action@v2
        if: github.event_name != 'release'
        with:
          files: src/main/resources/staticVars/VERSION
          replacements: dev-snapshot=dev-snapshot-${{ steps.vars.outputs.sha_short }}
      - name: Set branch in BRANCH file
        uses: datamonsters/replace-action@v2
        with:
          files: src/main/resources/staticVars/BRANCH
          replacements: IN-DEV=${{ steps.vars.outputs.branch }}
      - name: Set commit hash in COMMIT file
        uses: datamonsters/replace-action@v2
        with:
          files: src/main/resources/staticVars/COMMIT
          replacements: IN-DEV=${{ steps.vars.outputs.sha_short }}
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts.xml') }}
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          java-version: 12
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setting permissions
        run: chmod +x ./gradlew
      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./gradlew dependencies --refresh-dependencies
      - uses: actions/upload-artifact@v2
        name: Upload prepared repo to artifacts
        with:
          name: prepared-repo
          path: ${{ github.workspace }}
  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: prepare
    steps:
      - uses: actions/download-artifact@v2
        name: Download prepared repository
        with:
          name: prepared-repo
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts.xml') }}
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setting permissions
        run: chmod +x ./gradlew
      - name: Build with gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        name: Upload builded jar to artifacts
        with:
          name: build
          path: ${{ github.workspace }}/build/libs/${{ env.JAR_NAME }}
          retention-days: 1
      - uses: actions/upload-artifact@v2
        name: Upload builded repo to artifacts
        with:
          name: builded-repo
          path: ${{ github.workspace }}
  test:
    if: github.event_name != 'schedule'
    name: Test
    runs-on: ubuntu-20.04
    needs: Build
    steps:
      - uses: actions/download-artifact@v2
        name: Download prepared repository
        with:
          name: builded-repo
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts.xml') }}
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setting permissions
        run: chmod +x ./gradlew
      - name: Test with gradle
        run: ./gradlew test
  dokka:
    name: Generate Dokka
    runs-on: ubuntu-20.04
    needs: [prepare, build-docs]
    steps:
      - uses: actions/download-artifact@v2
        name: Download prepared repository
        with:
          name: prepared-repo
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts.xml') }}
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setting permissions
        run: chmod +x ./gradlew
      - name: Generate dokka html with gradle
        run: ./gradlew dokkaHtml
      - name: Generate dokka javadaoc with gradle
        run: ./gradlew dokkaJavadoc
      - uses: actions/download-artifact@v2
        name: Download builded documentation
        with:
          name: builded-docs
      - name: Move dokka files into documentation.
        run: mv /build/dokka/* site/
      - uses: actions/upload-artifact@v2
        name: Upload dokka documentation to artifacts
        with:
          name: dokka-docs
          path: ${{ github.workspace }}/site/
          retention-days: 1
  ci:
    name: Continuous integration
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    needs: [build, dokka, test, detekt]
    steps:
      - uses: actions/download-artifact@v2
        name: Download build
        with:
          name: build
      - uses: actions/download-artifact@v2
        name: Download dokka-docs
        with:
          name: dokka-docs
          path: docs/
      - uses: papeloto/action-zip@v1
        with:
          files: docs/
          dest: docs.zip
      - name: Upload docs to Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: docs.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build to Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ env.JAR_NAME }} application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ env.CI_DOCS_TO_GH_PAGES == 'true' }}
        name: Update live documentation on GH pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
      - name: Install SSH Key
        if: ${{ env.CI_DOCS_TO_SERVER == 'true' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
      - name: Deploy with rsync
        if: ${{ env.CI_DOCS_TO_SERVER == 'true' }}
        run: rsync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DOCUMENTATION_REMOTE_HOST_PATH }}
  cleanup:
    name: Cleanup
    runs-on: ubuntu-20.04
    continue-on-error: true
    if: always()
    needs: [prepare, test, build, dokka, ci, detekt, build-docs]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        name: Delete prepared repo artifact
        with:
          name: prepared-repo
      - uses: geekyeggo/delete-artifact@v1
        name: Delete prepared repo artifact
        with:
          name: builded-repo
      - uses: geekyeggo/delete-artifact@v1
        name: Delete prepared repo artifact
        with:
          name: builded-docs
  build-docs:
    if: github.event_name != 'schedule' && github.event_name != 'pull_request'
    name: Generate documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Setup MkDocs
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
      - name: Generate Documentation
        run: cd docs && mkdocs build && cd ..
      - uses: actions/upload-artifact@v2
        name: Upload builded files to artifacts
        with:
          name: builded-docs
          path: docs/site/
  detekt:
    name: Detekt code analysis
    needs: prepare
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        name: Download builded repository
        with:
          name: prepared-repo
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts.xml') }}
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setting permissions
        run: chmod +x ./gradlew
      - name: Perform detekt analysis
        run: ./gradlew detekt
